package com.dannbrown.databoxlib.lib

object LibData {
  object NAMES {
    const val IRON = "iron"
    const val GOLD = "gold"
    const val COAL = "coal"
    const val DIAMOND = "diamond"
    const val LAPIS_LAZULI = "lapis_lazuli"
    const val REDSTONE = "redstone"
    const val COPPER = "copper"
    const val SUGAR = "sugar"
    const val ADAMANTIUM = "adamantium"
    const val RAW_ADAMANTIUM = "raw_adamantium"
    const val ALUMINIUM = "aluminium"
    const val RAW_ALUMINIUM = "raw_aluminium"
    const val TIN = "tin"
    const val RAW_TIN = "raw_tin"
    const val STEEL = "steel"
    const val TUNGSTEN = "tungsten"
    const val RAW_TUNGSTEN = "raw_tungsten"
    const val TITANIUM = "titanium"
    const val BRONZE = "bronze"
    const val SILICA_CRYSTAL = "silica_crystal"
    const val SILICA = "silica"
    const val CARBON = "carbon"
    const val SULPHUR = "sulphur"
    const val PHOSPHORUS = "phosphorus"
    const val MAGNESIUM = "magnesium"
    const val GRAPHITE = "graphite"
    const val PERIDOT = "peridot"
    const val PHOSPHORITE = "phosphorite"
    const val PYRITE = "pyrite"
    const val OLIVINE = "olivine"
    const val NORITE = "norite"
    const val ANORTHOSITE = "anorthosite"
    const val ROSEATE = "roseate"
    const val HIMALAYAN_SALT = "himalayan_salt"
    const val RAW_HIMALAYAN_SALT = "raw_himalayan_salt"
    const val BROWN_SLATE = "brown_slate"
    const val RED_HEMATITE = "red_hematite"
    const val MOONSLATE = "moonslate"
    const val JOSHUA = "joshua"
    const val BRECCIA = "breccia"
  }

  // BLOCKS
  object BLOCKS {
    const val SILICA_GEL = "silica_gel"
    const val MAGMATIC_SILICA_GEL = "magmatic_silica_gel"
    const val STEEL_CASING = "steel_casing"
    const val STEEL_PURPLE_PANEL_CASING = "steel_purple_panel_casing"
    const val STEEL_BLUE_PANEL_CASING = "steel_blue_panel_casing"
    const val STEEL_ORANGE_PANEL_CASING = "steel_orange_panel_casing"
    const val STEEL_RED_PANEL_CASING = "steel_red_panel_casing"
    const val STEEL_GREEN_PANEL_CASING = "steel_green_panel_casing"
    const val STEEL_SCAFFOLDING = "steel_scaffolding"
    const val DESH_CASING = "desh_casing"
    const val DESH_PANEL_CASING = "desh_panel_casing"
    const val DESH_SCAFFOLDING = "desh_scaffolding"
    const val OSTRUM_CASING = "ostrum_casing"
    const val OSTRUM_PANEL_CASING = "ostrum_panel_casing"
    const val OSTRUM_SCAFFOLDING = "ostrum_scaffolding"
    const val CALORITE_CASING = "calorite_casing"
    const val CALORITE_PANEL_CASING = "calorite_panel_casing"
    const val CALORITE_SCAFFOLDING = "calorite_scaffolding"
    const val CARGO_BAY = "cargo_bay"
    const val MECHANICAL_COOLER = "mechanical_cooler"
    const val KINETIC_ELECTROLYZER = "kinetic_electrolyzer"
    const val PRESSURE_CHAMBER_CAP = "pressure_chamber_cap"
    const val OXYGEN_EMITTER = "oxygen_emitter"
    const val ASTEROID_ROCK = "asteroid_rock"
    const val DENSE_ASTEROID_ROCK = "dense_asteroid_rock"
    const val ANALOGIC_MACHINE = "analogic_machine"
    const val ROSEATE_GRAINS = "roseate_grains"
    const val SILT = "silt"
    const val RUST = "rust"
    const val SANDSTONE_PEBBLES = "sandstone_pebbles"
    const val RED_SANDSTONE_PEBBLES = "red_sandstone_pebbles"
    const val ROSEATE_SANDSTONE_PEBBLES = "roseate_sandstone_pebbles"
    const val BASALT_PEBBLES = "basalt_pebbles"
    const val MOON_SILT = "moon_silt"
    const val MOON_REGOLITH = "moon_regolith"
    const val MOON_ROCK = "moon_rock"
    const val MOON_COBBLESTONE = "moon_cobblestone"
    const val WALL_PANEL = "wall_panel"
    const val HULL_PANEL = "hull_panel"
  }

  object STICKERS {
    const val LAUGHING = "laughing"
    const val COOL = "cool"
    const val CRYING = "crying"
    const val LOVE = "love"
    const val SWEAT_SMILE = "sweat_smile"
    const val SCARY_FACE = "scary_face"
    const val EVIL_FACE = "evil_face"
    const val CREEPER_FACE = "creeper_face"
    const val FAKE_DIAMOND = "fake_diamond"
    const val TARGET_OVERLAY = "target_overlay"
    const val BRICK_OVERLAY = "brick_overlay"
    const val RED_ARROW = "red_arrow"
    const val GREEN_ARROW = "green_arrow"
    const val BLUE_ARROW = "blue_arrow"
    const val YELLOW_ARROW = "yellow_arrow"
    const val HAZARD = "hazard"
    const val RECYCLE = "recycle"
    const val WARNING = "warning"
    const val SAFETY_TAPE = "safety_tape"
    const val SAFETY_TAPE_CORNER = "safety_tape_corner"
    const val SAFETY_TAPE_T = "safety_tape_t"
    const val SAFETY_TAPE_CROSS = "safety_tape_cross"
  }

  // ITEMS
  object ITEMS {
    const val TIER_5_ROCKET = "tier_5_rocket"
    const val TIER_6_ROCKET = "tier_6_rocket"
    const val TIER_7_ROCKET = "tier_7_rocket"
    const val ADAMANTIUM_INGOT = "adamantium_ingot"
    const val ADAMANTIUM_FRAGMENT = "adamantium_fragment"
    const val BRONZE_INGOT = "bronze_ingot"
    const val BRONZE_NUGGET = "bronze_nugget"
    const val CRUSHED_RAW_DESH = "crushed_raw_desh"
    const val CRUSHED_RAW_OSTRUM = "crushed_raw_ostrum"
    const val CRUSHED_RAW_CALORITE = "crushed_raw_calorite"
    const val RAW_TIN = "raw_tin"
    const val CRUSHED_RAW_TIN = "crushed_raw_tin"
    const val TIN_INGOT = "tin_ingot"
    const val TIN_NUGGET = "tin_nugget"
    const val RAW_ALUMINIUM = "raw_aluminium"
    const val CRUSHED_RAW_ALUMINIUM = "crushed_raw_aluminium"
    const val ALUMINIUM_INGOT = "aluminium_ingot"
    const val ALUMINIUM_SHEET = "aluminium_sheet"
    const val ALUMINIUM_NUGGET = "aluminium_nugget"
    const val SILICA_GRAINS = "silica_grains"
    const val SILICA_CRYSTAL = "silica_crystal"
    const val REFINED_SILICON = "refined_silicon"
    const val RAW_GRAPHITE = "raw_graphite"
    const val RAW_CARBON = "raw_carbon"
    const val CARBON_GRIT = "carbon_grit"
    const val IRON_DUST = "iron_dust"
    const val STEEL_BLEND = "steel_blend"
    const val PHOSPHORUS_POWDER = "phosphorus_powder"
    const val SULPHUR = "sulphur"
    const val MAGNESIUM_DUST = "magnesium_dust"
    const val HIMALAYAN_SALT = "himalayan_salt"
    const val SALT = "salt"
    const val ROSE_QUARTZ_SHARD = "rose_quartz_shard"
    const val PERIDOT = "peridot"
    const val CATHODE_TUBE = "cathode_tube"
    const val RUBBER = "rubber"
    const val CONDENSED_LATEX = "condensed_latex"
    const val COTTON_SEEDS = "cotton_seeds"
    const val COTTON_PULP = "cotton_pulp"
    const val WATER_GEL_BUBBLE = "water_gel_bubble"
    const val LAVA_GEL_BUBBLE = "lava_gel_bubble"
  }

  object PLANTS {
    const val GUAYULE_SHRUB = "guayule_shrub"
    const val BUDDING_COTTON = "budding_cotton"
    const val COTTON = "cotton"
  }

  object FLUIDS {
    const val INK = "ink"
    const val GLOW_INK = "glow_ink"
    const val HARD_WATER = "hard_water"
    const val HYDROGEN = "hydrogen"
    const val NITROGEN = "nitrogen"
    const val OXYGEN = "oxygen"
    const val SULFURIC_ACID = "sulfuric_acid"
    const val NITRIC_ACID = "nitric_acid"
    const val CREOSOTE_OIL = "creosote_oil"
    const val LATEX = "latex"
    const val GASOLINE = "gasoline"
    const val ETHANOL = "ethanol"
    const val BIODIESEL = "biodiesel"
    const val KEROSENE = "kerosene"
    const val PROPANE = "propane"
    const val PLANT_OIL = "plant_oil"
    const val MOLTEN_IRON = "molten_iron"
    const val MOLTEN_STEEL = "molten_steel"
  }

  // ENCHANTMENTS
  object ENCHANTMENTS {
    const val BLINKING_STRIKE = "blinking_strike"
  }

  object RECIPES {
    const val ELECTROLYSIS = "electrolysis"
    const val COOLING = "cooling"
    const val PRESSURE_CHAMBER = "pressure_chamber"
  }

  object DAMAGE_SOURCES {
    const val GAS_SUFFOCATION = "databoxlib.gas_suffocation"
    const val MOLTEN_METAL = "databoxlib.molten_metal"
    const val ACID_CORROSION = "databoxlib.acid_corrosion"
  }
}